"""Initial tables

Revision ID: cd801f02edbf
Revises: 
Create Date: 2025-04-16 10:33:32.776336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd801f02edbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=mysql.ENUM('High', 'Medium', 'Low'),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'Medium'"))
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('High', 'Medium', 'Low'),
               existing_nullable=True,
               existing_server_default=sa.text("'Medium'"))
    # ### end Alembic commands ###
